const GOOGLE_SCRIPT_URL="https://script.google.com/macros/s/AKfycbzR6fFUpewGBnASPteL7n6uJ4m6GBWk43iTwjcRVH3Ckh_KdDydY0uTkAXf7jor-WZ2/exec";
const ADMIN_KEY="tdAuditAdminV3";
let adminSession=JSON.parse(sessionStorage.getItem(ADMIN_KEY)||"null");
let selectedVehicle=null, pendingVehicle=null, mediaStore={odo:[],spare:[],condition:[],other:[],parts:{}}, mediaTarget=null;
const BODY_PARTS=["Front Bumper","Rear Bumper","Bonnet","Roof","Front Left Fender","Front Right Fender","Rear Left Quarter Panel","Rear Right Quarter Panel","Front Left Door","Front Right Door","Rear Left Door","Rear Right Door","Left ORVM","Right ORVM","Front Windshield","Rear Windshield","Left Side Glass","Right Side Glass","Tailgate / Boot","Headlamp LH","Headlamp RH","Tail Lamp LH","Tail Lamp RH","Alloy / Wheel LH","Alloy / Wheel RH","Other Body Area"];

function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function status(id,msg,type){const e=document.getElementById(id);if(!e)return;e.textContent=msg;e.className="status show "+type}
function hide(id){const e=document.getElementById(id);if(e)e.className="status"}
function checkApi(){return !GOOGLE_SCRIPT_URL.includes("PASTE_YOUR")}
function apiGet(p){return fetch(GOOGLE_SCRIPT_URL+"?"+new URLSearchParams(p)).then(r=>r.json())}
function apiPost(p){return fetch(GOOGLE_SCRIPT_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(p)}).then(r=>r.json())}
function showSection(id,btn){document.querySelectorAll(".section").forEach(s=>s.classList.remove("active"));document.querySelectorAll(".nav button").forEach(b=>b.classList.remove("active"));document.getElementById(id).classList.add("active");if(btn)btn.classList.add("active");if(["branchSection","historySection","closingSection","adminSection"].includes(id))loadBranches();if(id==="dashboardSection"){if(adminSession)loadDashboard();else lockDashboard()}}
async function loadBranches(){try{const d=await apiGet({action:"getBranches"});if(!d.success)throw Error(d.message);["branchSelect","historyBranch","closingBranch","addBranchSelect","adminAuditBranch"].forEach(id=>{const e=document.getElementById(id);if(!e)return;const first=(id==="historyBranch"||id==="adminAuditBranch")?"<option value=''>All Branches</option>":"<option value=''>Select Branch</option>";e.innerHTML=first+(d.branches||[]).map(b=>`<option value="${esc(b)}">${esc(b)}</option>`).join("")})}catch(e){status("branchStatus",e.message,"error")}}

async function searchVehicle(){const n=document.getElementById("vehicleNumber").value.trim();if(!n)return status("searchStatus","Enter a vehicle number.","error");try{hide("searchStatus");const d=await apiGet({action:"searchVehicle",vehicleNumber:n});if(!d.success)return status("searchStatus",d.message,"error");pendingVehicle=d.vehicle;document.getElementById("vehicleResult").innerHTML=`<div class="vehicle-card"><div class="vehicle-head"><div><strong>${esc(d.vehicle.vehicleNumber)}</strong><div class="muted">${esc(d.vehicle.vehicleName)} • ${esc(d.vehicle.variant)} • ${esc(d.vehicle.fuel)} • ${esc(d.vehicle.branch)}</div></div><button class="btn success" onclick="openVehicleModal()">VIEW DETAILS / START</button></div></div>`}catch(e){status("searchStatus",e.message,"error")}}
function clearSearch(){document.getElementById("vehicleNumber").value="";document.getElementById("vehicleResult").innerHTML="";hide("searchStatus")}
function openVehicleModal(){if(!pendingVehicle)return;document.getElementById("modalVehicle").innerHTML=`<div class="vehicle-card"><p><b>Vehicle Number:</b> ${esc(pendingVehicle.vehicleNumber)}</p><p><b>Vehicle Name:</b> ${esc(pendingVehicle.vehicleName)}</p><p><b>Variant:</b> ${esc(pendingVehicle.variant)}</p><p><b>Fuel:</b> ${esc(pendingVehicle.fuel)}</p><p><b>Branch:</b> ${esc(pendingVehicle.branch)}</p></div>`;document.getElementById("vehicleModal").classList.add("show")}
function closeVehicleModal(){document.getElementById("vehicleModal").classList.remove("show")}
function confirmVehicleAudit(){selectedVehicle=pendingVehicle;closeVehicleModal();startAudit()}
async function loadBranchVehicles(){const b=document.getElementById("branchSelect").value;if(!b)return status("branchStatus","Select a branch.","error");try{const d=await apiGet({action:"getVehiclesByBranch",branch:b});if(!d.success)throw Error(d.message);document.getElementById("branchResults").style.display="block";document.getElementById("branchCount").textContent=`Total vehicles in ${b}: ${d.count}`;document.getElementById("branchTableBody").innerHTML=(d.vehicles||[]).map((v,i)=>`<tr><td>${esc(v.vehicleNumber)}</td><td>${esc(v.vehicleName)}</td><td>${esc(v.variant)}</td><td>${esc(v.fuel)}</td><td>${esc(v.branch)}</td><td><button class="btn success" onclick="branchVehicle(${i})">AUDIT</button></td></tr>`).join("");window._branchVehicles=d.vehicles||[]}catch(e){status("branchStatus",e.message,"error")}}
function branchVehicle(i){pendingVehicle=window._branchVehicles[i];openVehicleModal()}
function startAudit(){document.getElementById("auditForm").style.display="block";document.getElementById("selectedVehicleBox").textContent=`Selected: ${selectedVehicle.vehicleNumber} — ${selectedVehicle.vehicleName} — ${selectedVehicle.branch}`;document.getElementById("auditVehicleNumber").textContent=selectedVehicle.vehicleNumber;document.getElementById("auditVehicleMeta").textContent=`${selectedVehicle.vehicleName} • ${selectedVehicle.variant} • ${selectedVehicle.fuel} • ${selectedVehicle.branch}`;buildParts();resetAudit(false);renderSingleMedia("odoMediaArea","odo");document.querySelectorAll(".nav button").forEach(b=>{if(b.textContent==="Start Audit")b.click()});window.scrollTo({top:0,behavior:"smooth"});apiPost({action:"recordAttendance",branch:selectedVehicle.branch,auditorName:document.getElementById("auditorName").value||"Pending",employeeId:document.getElementById("auditorId").value||"Pending",attendanceAction:"VEHICLE_OPENED"}).catch(()=>{})}
function toggleBlock(id,on){document.getElementById(id).style.display=on?"block":"none"}
function radio(name){const e=document.querySelector(`input[name="${name}"]:checked`);return e?e.value:""}
function calcKm(){const a=Number(document.getElementById("logBookKm").value),b=Number(document.getElementById("odometerKm").value),d=(a&&b)?b-a:"";document.getElementById("kmDifference").value=d;document.getElementById("kmStatus").textContent=(d==="")?"Enter both kilometer values.":(d===0?"No kilometer difference.":`Difference: ${d>0?"+":""}${d} km`)}
function buildParts(){document.getElementById("parts").innerHTML=BODY_PARTS.map(p=>`<label class="part"><input type="checkbox" value="${esc(p)}" onchange="renderPartMedia()"> ${esc(p)}</label>`).join("")}
function mediaButtons(key){return `<div class="actions"><button class="btn secondary" onclick="openMedia('${key}','photo')">TAKE PHOTO</button><button class="btn secondary" onclick="openMedia('${key}','video')">TAKE VIDEO</button><button class="btn secondary" onclick="openMedia('${key}','file')">ADD FILE</button></div><div class="media-row" id="mediaRow_${btoa(unescape(encodeURIComponent(key))).replace(/=/g,'')}"></div>`}
function targetId(key){return btoa(unescape(encodeURIComponent(key))).replace(/=/g,'')}
function renderMedia(key){const arr=mediaArray(key),el=document.getElementById("mediaRow_"+targetId(key));if(!el)return;el.innerHTML=arr.map((m,i)=>`<div class="media-item">${m.type.startsWith("video")?`<video src="${m.data}" controls></video>`:`<img src="${m.data}" alt="">`}<div><span>${esc(m.name).slice(0,18)}</span><button class="smallbtn" onclick="removeMedia('${key.replace(/'/g,"\\'")}',${i})">REMOVE</button></div></div>`).join("")}
function mediaArray(key){if(key==="odo")return mediaStore.odo;if(key==="spare")return mediaStore.spare;if(key==="condition")return mediaStore.condition;if(key==="other")return mediaStore.other;if(key.startsWith("part:")){const p=key.slice(5);if(!mediaStore.parts[p])mediaStore.parts[p]=[];return mediaStore.parts[p]}return []}
function addMedia(key,file){mediaArray(key).push(file);renderMedia(key)}
function removeMedia(key,i){mediaArray(key).splice(i,1);renderMedia(key)}
function renderSingleMedia(container,key){document.getElementById(container).innerHTML=`<div class="media-box"><b>Evidence</b>${mediaButtons(key)}</div>`;renderMedia(key)}
function renderPartMedia(){const selected=[...document.querySelectorAll("#parts input:checked")].map(x=>x.value);document.getElementById("partMediaArea").innerHTML=selected.map(p=>`<div class="media-box"><b>${esc(p)}</b>${mediaButtons("part:"+p)}</div>`).join("");selected.forEach(p=>renderMedia("part:"+p))}
function renderConditionMedia(){renderSingleMedia("conditionMedia","condition")}
function renderSpareMedia(){renderSingleMedia("spareMedia","spare")}
function openMedia(key,kind){mediaTarget=key;const el=document.getElementById(kind==="photo"?"photoInput":kind==="video"?"videoInput":"fileInput");el.value="";el.onchange=async()=>{for(const f of [...el.files]){try{addMedia(key,await fileToData(f))}catch(e){alert(e.message)}}};el.click()}
function fileToData(f){return new Promise((resolve,reject)=>{if(f.size>25*1024*1024)reject(Error("File is larger than 25 MB. Use a shorter video or smaller file."));const r=new FileReader();r.onload=()=>resolve({name:f.name,type:f.type||"application/octet-stream",data:r.result});r.onerror=()=>reject(Error("Could not read file."));r.readAsDataURL(f)})}
function collectAudit(){const damage=radio("damage"),parts=[...document.querySelectorAll("#parts input:checked")].map(x=>x.value),a={action:"submitAudit",vehicle:selectedVehicle,logBookKm:Number(document.getElementById("logBookKm").value)||0,odometerKm:Number(document.getElementById("odometerKm").value)||0,odoVariation:radio("odo"),odoRemarks:document.getElementById("odoRemarks").value.trim(),damage,damageParts:parts,vehicleCondition:radio("condition"),spareWheel:radio("spare"),otherIssue:radio("other"),otherRemarks:document.getElementById("otherRemarks").value.trim(),auditorName:document.getElementById("auditorName").value.trim(),auditorId:document.getElementById("auditorId").value.trim(),media:{odo:mediaStore.odo,spare:mediaStore.spare,condition:mediaStore.condition,other:mediaStore.other,parts:mediaStore.parts}};return a}
async function submitAudit(){if(!selectedVehicle)return status("auditStatus","Select a vehicle first.","error");const a=collectAudit();if(!a.logBookKm||!a.odometerKm||!a.odoVariation||!a.damage||!a.vehicleCondition||!a.spareWheel||!a.otherIssue||!a.auditorName||!a.auditorId)return status("auditStatus","Complete kilometer, checklist and auditor fields.","error");if(a.odoVariation==="Yes"&&!a.odoRemarks)return status("auditStatus","Add odometer variation remarks.","error");if(a.damage==="Yes"&&!a.damageParts.length)return status("auditStatus","Select at least one affected body part.","error");if(a.otherIssue==="Yes"&&!a.otherRemarks)return status("auditStatus","Add other issue remarks.","error");const btn=document.getElementById("submitAuditBtn");btn.disabled=true;status("auditStatus","Saving audit and evidence. Please wait...","info");try{const d=await apiPost(a);if(!d.success)throw Error(d.message);status("auditStatus",`Audit saved: ${d.auditId}. Evidence files: ${d.mediaCount}`,"success");setTimeout(()=>resetAudit(true),1200)}catch(e){status("auditStatus","Could not save audit: "+e.message,"error")}finally{btn.disabled=false}}
function resetAudit(clear=true){mediaStore={odo:[],spare:[],condition:[],other:[],parts:{}};document.querySelectorAll('#auditForm input[type="radio"],#auditForm input[type="checkbox"]').forEach(x=>x.checked=false);["logBookKm","odometerKm","kmDifference","odoRemarks","otherRemarks","auditorName","auditorId"].forEach(id=>document.getElementById(id).value="");["odoIssue","damageIssue","otherIssue"].forEach(id=>toggleBlock(id,false));document.getElementById("partMediaArea").innerHTML="";document.getElementById("conditionMedia").innerHTML="";document.getElementById("spareMedia").innerHTML="";document.getElementById("odoMediaArea").innerHTML="";document.getElementById("media_other").innerHTML="";if(clear){selectedVehicle=null;document.getElementById("auditForm").style.display="none";document.getElementById("selectedVehicleBox").textContent="Select a vehicle from Search or Branches."}}
async function loadHistory(){try{status("historyStatus","Loading history...","info");const d=await apiGet({action:"getAuditHistory",vehicleNumber:document.getElementById("historyVehicle").value.trim(),branch:document.getElementById("historyBranch").value});if(!d.success)throw Error(d.message);hide("historyStatus");const rs=d.records||[];document.getElementById("historyResults").innerHTML=rs.length?`<div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Time</th><th>Vehicle</th><th>Branch</th><th>Auditor</th><th>Log KM</th><th>Odo KM</th><th>Diff</th><th>Variation</th><th>Damage</th><th>Condition</th><th>Spare</th><th>Other</th><th>Media</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${esc(r.auditId)}</td><td>${esc(r.timestamp)}</td><td>${esc(r.vehicleNumber)}</td><td>${esc(r.branch)}</td><td>${esc(r.auditorName)}</td><td>${esc(r.logBookKm)}</td><td>${esc(r.odometerKm)}</td><td>${esc(r.kmDifference)}</td><td>${esc(r.odoVariation)}</td><td>${esc(r.damage)}</td><td>${esc(r.vehicleCondition)}</td><td>${esc(r.spareWheel)}</td><td>${esc(r.otherIssue)}</td><td>${esc(r.mediaCount)}</td></tr>`).join("")}</tbody></table></div>`:"<div class='muted'>No audit records found.</div>"}catch(e){status("historyStatus",e.message,"error")}}
function addTransferRow(){const wrap=document.getElementById("transferRows"),row=document.createElement("div");row.className="transfer-row";row.innerHTML=`<div><label>Other Showroom</label><input class="trBranch"></div><div><label>Count</label><input class="trCount" type="number" min="0" value="0" oninput="syncTransferTotal()"></div><div><label>Details</label><input class="trDetails" placeholder="Vehicle numbers / reason"></div><button class="btn danger" onclick="this.parentElement.remove();syncTransferTotal()">REMOVE</button>`;wrap.appendChild(row);syncTransferTotal()}
function syncTransferTotal(){let n=0;document.querySelectorAll(".trCount").forEach(e=>n+=Number(e.value)||0);document.getElementById("transferTotal").value=n;recalcClosing()}
function recalcClosing(){const total=Number(document.getElementById("totalTD").value)||0,vals=["inShowroom","outTD","underWashing","underBodyShop","transferTotal"].map(id=>Number(document.getElementById(id).value)||0),accounted=vals.reduce((a,b)=>a+b,0),diff=accounted-total;document.getElementById("accountedTotal").textContent=accounted;document.getElementById("balanceText").textContent=!total?"Enter TOTAL TEST DRIVE.":diff===0?"BALANCED — Accounted count equals Total Test Drive.":diff>0?`OVER BY ${diff} VEHICLE(S) — CHECK.`:`SHORT BY ${Math.abs(diff)} VEHICLE(S) — CHECK.`}
function transferDetails(){return [...document.querySelectorAll(".transfer-row")].map(r=>({showroom:r.querySelector(".trBranch").value.trim(),count:Number(r.querySelector(".trCount").value)||0,details:r.querySelector(".trDetails").value.trim()})).filter(x=>x.showroom||x.count||x.details)}
async function submitBranchClosing(){const total=Number(document.getElementById("totalTD").value)||0,accounted=Number(document.getElementById("accountedTotal").textContent)||0;if(!document.getElementById("closingBranch").value||!document.getElementById("closingDate").value||!total||!document.getElementById("closingAuditor").value.trim()||!document.getElementById("closingAuditorId").value.trim())return status("closingStatus","Complete branch, date, total and auditor details.","error");if(accounted!==total)return status("closingStatus",`Cannot save: TOTAL ${total}, ACCOUNTED ${accounted}.`,"error");try{const d=await apiPost({action:"submitBranchClosing",branch:document.getElementById("closingBranch").value,auditDate:document.getElementById("closingDate").value,totalTD:total,inShowroom:Number(document.getElementById("inShowroom").value)||0,outForTestDrive:Number(document.getElementById("outTD").value)||0,underWashing:Number(document.getElementById("underWashing").value)||0,underBodyShop:Number(document.getElementById("underBodyShop").value)||0,transferToOtherShowrooms:Number(document.getElementById("transferTotal").value)||0,transferDetails:transferDetails(),auditorName:document.getElementById("closingAuditor").value.trim(),employeeId:document.getElementById("closingAuditorId").value.trim(),remarks:document.getElementById("closingRemarks").value.trim()});if(!d.success)throw Error(d.message);status("closingStatus","Branch closing saved: "+d.closingId+(d.ppt&&d.ppt.success?" • PPT v"+d.ppt.version+" created":""),"success");if(d.ppt&&d.ppt.success){document.getElementById("pptResults").innerHTML=`<div class="status show success">Automatic PPT ready: <a href="${esc(d.ppt.presentationUrl)}" target="_blank">OPEN GOOGLE SLIDES</a> • <a href="${esc(d.ppt.pptUrl)}" target="_blank">DOWNLOAD PPTX</a></div>`;showSection("adminSection");}else if(d.ppt&&!d.ppt.success){status("closingStatus","Closing saved, but PPT generation failed: "+d.ppt.message,"warn")}}catch(e){status("closingStatus",e.message,"error")}}
function resetClosing(){["closingDate","totalTD","inShowroom","outTD","underWashing","underBodyShop","transferTotal","closingAuditor","closingAuditorId","closingRemarks"].forEach(id=>document.getElementById(id).value="");document.getElementById("transferRows").innerHTML="";recalcClosing()}
async function unlockAdmin(){const u=document.getElementById("adminUsername").value.trim(),p=document.getElementById("adminPassword").value;if(!u||!p)return status("adminLoginStatus","Enter username and password.","error");try{const d=await apiGet({action:"verifyAdmin",username:u,password:p});if(!d.success)return status("adminLoginStatus",d.message,"error");adminSession={username:u,password:p};sessionStorage.setItem(ADMIN_KEY,JSON.stringify(adminSession));showAdmin();loadDashboard();status("adminLoginStatus","Admin unlocked.","success")}catch(e){status("adminLoginStatus",e.message,"error")}}
function showAdmin(){document.getElementById("adminLock").style.display="none";document.getElementById("adminContent").style.display="block";if(document.getElementById("adminAuditResults"))loadAdminAudits(50)}
function lockAdmin(){adminSession=null;sessionStorage.removeItem(ADMIN_KEY);document.getElementById("adminLock").style.display="block";document.getElementById("adminContent").style.display="none";lockDashboard()}
function lockDashboard(){document.getElementById("dashboardLock").style.display="block";document.getElementById("dashboardContent").style.display="none"}
async function addBranch(){if(!adminSession)return;try{const d=await apiPost({action:"addBranch",branch:document.getElementById("newBranch").value.trim(),adminUsername:adminSession.username,adminPassword:adminSession.password});if(!d.success)throw Error(d.message);status("addBranchStatus",d.message,"success");document.getElementById("newBranch").value="";loadBranches()}catch(e){status("addBranchStatus",e.message,"error")}}
async function addVehicle(){if(!adminSession)return;try{const d=await apiPost({action:"addVehicle",vehicleNumber:document.getElementById("addVehicleNumber").value.trim(),vehicleName:document.getElementById("addVehicleName").value.trim(),variant:document.getElementById("addVariant").value.trim(),fuel:document.getElementById("addFuel").value,branch:document.getElementById("addBranchSelect").value,adminUsername:adminSession.username,adminPassword:adminSession.password});if(!d.success)throw Error(d.message);status("addVehicleStatus",d.message,"success");["addVehicleNumber","addVehicleName","addVariant"].forEach(id=>document.getElementById(id).value="");loadBranches()}catch(e){status("addVehicleStatus",e.message,"error")}}
async function loadDashboard(){if(!adminSession)return lockDashboard();document.getElementById("dashboardLock").style.display="none";document.getElementById("dashboardContent").style.display="block";status("dashStatus","Loading live dashboard...","info");try{const d=await apiPost({action:"getAdminDashboard",adminUsername:adminSession.username,adminPassword:adminSession.password});if(!d.success)throw Error(d.message);const stats=[["TOTAL TD VEHICLES",d.totalVehicles],["AUDITS COMPLETED",d.totalAudits],["AUDITS WITH ISSUES",d.openIssues],["VEHICLES NOT YET AUDITED",d.unAuditedVehicles],["TODAY'S AUDITS",d.todayAudits],["BRANCHES",d.totalBranches]];document.getElementById("dashStats").innerHTML=stats.map(x=>`<div class="stat dashboard-stat"><div class="lbl">${x[0]}</div><div class="num">${x[1]}</div></div>`).join("");const issue=d.issueSummary||{};document.getElementById("issueSummary").innerHTML=`<div class="metric-list"><div><span>ODO VARIATION</span><strong>${issue.odo||0}</strong></div><div><span>DAMAGE / PAINT</span><strong>${issue.damage||0}</strong></div><div><span>NOT CLEAN</span><strong>${issue.condition||0}</strong></div><div><span>SPARE WHEEL MISSING</span><strong>${issue.spare||0}</strong></div><div><span>OTHER ISSUES</span><strong>${issue.other||0}</strong></div></div>`;const coverage=d.totalVehicles?Math.round((d.auditedVehicleCount/d.totalVehicles)*100):0;document.getElementById("coverageSummary").innerHTML=`<div class="coverage-ring"><strong>${coverage}%</strong><span>vehicle audit coverage</span></div><div class="coverage-meta"><div><span>Vehicles audited</span><b>${d.auditedVehicleCount}</b></div><div><span>Pending first audit</span><b>${d.unAuditedVehicles}</b></div><div><span>Issue audit rate</span><b>${d.totalAudits?Math.round((d.openIssues/d.totalAudits)*100):0}%</b></div></div>`;document.getElementById("branchDashboard").innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Branch</th><th>TD Vehicles</th><th>Audited Vehicles</th><th>Coverage</th><th>Audits</th><th>Issues</th><th>Latest Closing</th><th>Status</th></tr></thead><tbody>${(d.branches||[]).map(b=>`<tr><td><strong>${esc(b.branch)}</strong></td><td>${b.vehicleCount}</td><td>${b.auditedVehicleCount}</td><td><span class="score-badge ${b.coveragePct>=90?'good':b.coveragePct>=60?'warn':'bad'}">${b.coveragePct}%</span></td><td>${b.auditCount}</td><td>${b.openIssues}</td><td>${esc(b.latestClosing||'')}</td><td>${esc(b.closingStatus)}</td></tr>`).join("")}</tbody></table></div>`;renderRecentAudits(d.recentAudits||[]);renderAttendance(d.attendance);status("dashStatus",`Dashboard refreshed at ${new Date().toLocaleTimeString()}.`,"success")}catch(e){status("dashStatus","Dashboard load failed: "+e.message,"error")}}
function renderRecentAudits(rs){document.getElementById("recentAuditsDashboard").innerHTML=rs.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Time</th><th>Audit ID</th><th>Vehicle</th><th>Branch</th><th>Auditor</th><th>Issues</th><th>Media</th><th></th></tr></thead><tbody>${rs.map(r=>`<tr><td>${esc(r.timestamp)}</td><td>${esc(r.auditId)}</td><td>${esc(r.vehicleNumber)}</td><td>${esc(r.branch)}</td><td>${esc(r.auditorName)}</td><td><span class="score-badge ${r.issueCount?'bad':'good'}">${r.issueCount?'ISSUE':'OK'}</span></td><td>${r.mediaCount}</td><td><button class="small-action" onclick="viewAuditDetails('${String(r.auditId).replace(/'/g,"\\'")}')">VIEW FULL AUDIT</button></td></tr>`).join("")}</tbody></table></div>`:"<div class='muted'>No audits available.</div>"}
function renderAttendance(a){if(!a||!a.dates.length)return document.getElementById("attendanceChart").innerHTML="<div class='muted'>No attendance records yet.</div>";let h="<table><thead><tr><th>Branch</th>"+a.dates.map(d=>`<th>${esc(d)}</th>`).join("")+"</tr></thead><tbody>"+a.series.map(s=>`<tr><td>${esc(s.branch)}</td>${s.values.map(v=>`<td>${v}</td>`).join("")}</tr>`).join("")+"</tbody></table>";document.getElementById("attendanceChart").innerHTML=h}
async function loadAdminAudits(limit){if(!adminSession)return showAdmin();const vehicle=document.getElementById("adminAuditVehicle").value.trim(),branch=document.getElementById("adminAuditBranch").value;status("adminAuditStatus","Loading audit records...","info");try{const d=await apiPost({action:"getAdminAudits",vehicleNumber:vehicle,branch:branch,limit:limit||100,adminUsername:adminSession.username,adminPassword:adminSession.password});if(!d.success)throw Error(d.message);const rs=d.records||[];document.getElementById("adminAuditResults").innerHTML=rs.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Time</th><th>Audit ID</th><th>Vehicle</th><th>Branch</th><th>Auditor</th><th>ODO</th><th>Damage</th><th>Condition</th><th>Spare</th><th>Other</th><th>Media</th><th></th></tr></thead><tbody>${rs.map(r=>`<tr><td>${esc(r.timestamp)}</td><td>${esc(r.auditId)}</td><td>${esc(r.vehicleNumber)}</td><td>${esc(r.branch)}</td><td>${esc(r.auditorName)}</td><td>${esc(r.odoVariation)}</td><td>${esc(r.damage)}</td><td>${esc(r.vehicleCondition)}</td><td>${esc(r.spareWheel)}</td><td>${esc(r.otherIssue)}</td><td>${r.mediaCount}</td><td><button class="small-action" onclick="viewAuditDetails('${String(r.auditId).replace(/'/g,"\\'")}')">OPEN DETAILS</button></td></tr>`).join("")}</tbody></table></div>`:"<div class='muted'>No audit records found.</div>";status("adminAuditStatus",`${rs.length} audit record(s) loaded.`,"success")}catch(e){status("adminAuditStatus",e.message,"error")}}
function closeAuditDetail(){document.getElementById("auditDetailModal").classList.remove("show")}
function mediaHtml(m){const type=String(m.mimeType||"");const preview=m.previewUrl||m.driveUrl||"";const title=esc(m.category||m.originalName||"Evidence");if(type.indexOf("image/")===0&&preview)return `<div class="evidence-item"><img src="${esc(preview)}" alt="${title}" loading="lazy"><div class="evidence-caption"><strong>${title}</strong><span>${esc(m.originalName||"")}</span><a href="${esc(m.driveUrl)}" target="_blank">OPEN IN DRIVE</a></div></div>`;if(type.indexOf("video/")===0&&preview)return `<div class="evidence-item"><video src="${esc(preview)}" controls preload="metadata"></video><div class="evidence-caption"><strong>${title}</strong><span>${esc(m.originalName||"")}</span><a href="${esc(m.driveUrl)}" target="_blank">OPEN IN DRIVE</a></div></div>`;return `<div class="evidence-file"><strong>${title}</strong><span>${esc(m.originalName||"")}</span><a href="${esc(m.driveUrl)}" target="_blank">OPEN FILE</a></div>`}
async function viewAuditDetails(auditId){if(!adminSession)return;const box=document.getElementById("auditDetailContent");box.innerHTML="<div class='muted'>Loading full audit and evidence...</div>";document.getElementById("auditDetailModal").classList.add("show");try{const d=await apiPost({action:"getAdminAuditDetails",auditId: auditId,adminUsername:adminSession.username,adminPassword:adminSession.password});if(!d.success)throw Error(d.message);const a=d.audit||{};document.getElementById("auditDetailSubtitle").textContent=`${a.vehicleNumber||""} • ${a.branch||""} • ${a.timestamp||""}`;const fields=[['Audit ID',a.auditId],['Vehicle',a.vehicleNumber],['Vehicle Name',a.vehicleName],['Variant',a.variant],['Fuel',a.fuel],['Branch',a.branch],['Log Book KM',a.logBookKm],['Odometer KM',a.odometerKm],['Difference',a.kmDifference],['ODO Verification',a.odoVariation],['ODO Remarks',a.odoRemarks],['Damage',a.damage],['Affected Parts',a.damageParts],['Vehicle Condition',a.vehicleCondition],['Spare Wheel',a.spareWheel],['Other Issue',a.otherIssue],['Other Remarks',a.otherRemarks],['Auditor',a.auditorName],['Employee ID',a.auditorId]];box.innerHTML=`<div class="detail-grid">${fields.map(x=>`<div class="detail-field"><span>${esc(x[0])}</span><strong>${esc(x[1]??'')}</strong></div>`).join("")}</div><h3 style="margin-top:18px">Captured Evidence (${(d.media||[]).length})</h3><div class="evidence-grid">${(d.media||[]).map(mediaHtml).join("")||"<div class='muted'>No media was attached to this audit.</div>"}</div>`}catch(e){box.innerHTML=`<div class='status show error'>${esc(e.message)}</div>`}}
async function createBranchPpt(){if(!adminSession)return showAdmin();const branch=document.getElementById("pptBranch").value,date=document.getElementById("pptAuditDate").value;if(!branch||!date)return status("pptStatus","Select branch and audit date.","error");status("pptStatus","Creating Branch Audit PPT...","info");try{const d=await apiPost({action:"createBranchPpt",branch:branch,auditDate:date,adminUsername:adminSession.username,adminPassword:adminSession.password,createdBy:adminSession.username});if(!d.success)throw Error(d.message);document.getElementById("pptResults").innerHTML=`<div class="status show success">Version ${esc(d.version)} ready: <a href="${esc(d.presentationUrl)}" target="_blank">OPEN GOOGLE SLIDES</a> • <a href="${esc(d.pptUrl)}" target="_blank">DOWNLOAD PPTX</a></div>`;status("pptStatus","Presentation created successfully.","success");loadBranchPpts()}catch(e){status("pptStatus","PPT generation failed: "+e.message,"error")}}
async function loadBranchPpts(){try{const branch=document.getElementById("pptBranch").value;const d=await apiGet({action:"getBranchPpts",branch:branch});if(!d.success)throw Error(d.message);document.getElementById("pptResults").innerHTML=d.presentations.length?`<h4 style="margin-top:16px">Presentation History</h4><div class="table-wrap"><table class="table"><thead><tr><th>Created</th><th>Branch</th><th>Audit Date</th><th>Version</th><th>Created By</th><th>Slides</th><th>Issues</th><th>Google Slides</th><th>PPTX</th></tr></thead><tbody>${d.presentations.map(r=>`<tr><td>${esc(r.createdAt)}</td><td>${esc(r.branch)}</td><td>${esc(r.auditDate)}</td><td>v${esc(r.version)}</td><td>${esc(r.createdBy)}</td><td>${esc(r.slideCount||"—")}</td><td>${esc(r.issueCount||"—")}</td><td><a target="_blank" href="${esc(r.presentationUrl)}">OPEN</a></td><td><a target="_blank" href="${esc(r.pptUrl)}">DOWNLOAD</a></td></tr>`).join("")}</tbody></table></div>`:"<div class='muted'>No branch presentations generated yet.</div>"}catch(e){status("pptStatus",e.message,"error")}}
async function generateReports(){if(!adminSession)return lockDashboard();status("dashStatus","Generating Google Sheet, Excel and PDF...","info");try{const d=await apiPost({action:"generateReports",adminUsername:adminSession.username,adminPassword:adminSession.password});if(!d.success)throw Error(d.message);document.getElementById("dashboardReports").innerHTML=`<div class="status show success">Reports ready: <a href="${d.googleSheetUrl}" target="_blank">Google Sheet</a> • <a href="${d.excelUrl}" target="_blank">Excel</a> • <a href="${d.pdfUrl}" target="_blank">PDF</a></div>`;status("dashStatus","Reports generated.","success")}catch(e){status("dashStatus","Report generation failed: "+e.message,"error")}}
async function loadReportLinks(){try{const d=await apiGet({action:"getReportLinks"});if(!d.success)throw Error(d.message);document.getElementById("reportLinksHistory").innerHTML=d.reports.length?`<h3 style="margin-top:16px">Generated Reports</h3><div class="table-wrap"><table class="table"><thead><tr><th>Created</th><th>Google Sheet</th><th>Excel</th><th>PDF</th></tr></thead><tbody>${d.reports.map(r=>`<tr><td>${esc(r.createdAt)}</td><td><a target="_blank" href="${r.sheetUrl}">OPEN</a></td><td><a target="_blank" href="${r.excelUrl}">DOWNLOAD</a></td><td><a target="_blank" href="${r.pdfUrl}">DOWNLOAD</a></td></tr>`).join("")}</tbody></table></div>`:"<div class='muted'>No reports generated yet.</div>"}catch(e){status("historyStatus",e.message,"error")}}
function init(){if(adminSession){showAdmin();loadDashboard()}loadBranches();buildParts();document.getElementById("closingDate").value=new Date().toISOString().slice(0,10);document.getElementById("pptAuditDate").value=new Date().toISOString().slice(0,10)}
init();
