
const GOOGLE_SCRIPT_URL="https://script.google.com/macros/s/AKfycbzR6fFUpewGBnASPteL7n6uJ4m6GBWk43iTwjcRVH3Ckh_KdDydY0uTkAXf7jor-WZ2/exec";
const ADMIN_KEY="tdAuditAdminV3";
let adminSession=JSON.parse(sessionStorage.getItem(ADMIN_KEY)||"null");
let selectedVehicle=null, pendingVehicle=null, mediaStore={odo:[],spare:[],condition:[],other:[],parts:{}}, mediaTarget=null;
const BODY_PARTS=["Front Bumper","Rear Bumper","Bonnet","Roof","Front Left Fender","Front Right Fender","Rear Left Quarter Panel","Rear Right Quarter Panel","Front Left Door","Front Right Door","Rear Left Door","Rear Right Door","Left ORVM","Right ORVM","Front Windshield","Rear Windshield","Left Side Glass","Right Side Glass","Tailgate / Boot","Headlamp LH","Headlamp RH","Tail Lamp LH","Tail Lamp RH","Alloy / Wheel LH","Alloy / Wheel RH","Other Body Area"];

function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function status(id,msg,type){const e=document.getElementById(id);if(!e)return;e.textContent=msg;e.className="status show "+type}
function hide(id){const e=document.getElementById(id);if(e)e.className="status"}
function checkApi(){return !GOOGLE_SCRIPT_URL.includes("PASTE_YOUR")}
function apiGet(p){return fetch(GOOGLE_SCRIPT_URL+"?"+new URLSearchParams(p)).then(r=>r.json())}
function apiPost(p){return fetch(GOOGLE_SCRIPT_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(p)}).then(r=>r.json())}
function showSection(id,btn){document.querySelectorAll(".section").forEach(s=>s.classList.remove("active"));document.querySelectorAll(".nav button").forEach(b=>b.classList.remove("active"));document.getElementById(id).classList.add("active");if(btn)btn.classList.add("active");if(["branchSection","historySection","closingSection","adminSection"].includes(id))loadBranches();if(id==="dashboardSection"){if(adminSession)loadDashboard();else lockDashboard()}}
async function loadBranches(){try{const d=await apiGet({action:"getBranches"});if(!d.success)throw Error(d.message);window._branches=d.branches||[];["branchSelect","historyBranch","closingBranch","addBranchSelect"].forEach(id=>{const e=document.getElementById(id);if(!e)return;const first=id==="historyBranch"?"<option value=''>All Branches</option>":"<option value=''>Select Branch</option>";e.innerHTML=first+(d.branches||[]).map(b=>`<option value="${esc(b)}">${esc(b)}</option>`).join("")})}catch(e){status("branchStatus",e.message,"error")}}

async function searchVehicle(){const n=document.getElementById("vehicleNumber").value.trim();if(!n)return status("searchStatus","Enter a vehicle number.","error");try{hide("searchStatus");const d=await apiGet({action:"searchVehicle",vehicleNumber:n});if(!d.success)return status("searchStatus",d.message,"error");pendingVehicle=d.vehicle;document.getElementById("vehicleResult").innerHTML=`<div class="vehicle-card"><div class="vehicle-head"><div><strong>${esc(d.vehicle.vehicleNumber)}</strong><div class="muted">${esc(d.vehicle.vehicleName)} • ${esc(d.vehicle.variant)} • ${esc(d.vehicle.fuel)} • ${esc(d.vehicle.branch)}</div></div><button class="btn success" onclick="openVehicleModal()">VIEW DETAILS / START</button></div></div>`}catch(e){status("searchStatus",e.message,"error")}}
function clearSearch(){document.getElementById("vehicleNumber").value="";document.getElementById("vehicleResult").innerHTML="";hide("searchStatus")}
function openVehicleModal(){if(!pendingVehicle)return;document.getElementById("modalVehicle").innerHTML=`<div class="vehicle-card"><p><b>Vehicle Number:</b> ${esc(pendingVehicle.vehicleNumber)}</p><p><b>Vehicle Name:</b> ${esc(pendingVehicle.vehicleName)}</p><p><b>Variant:</b> ${esc(pendingVehicle.variant)}</p><p><b>Fuel:</b> ${esc(pendingVehicle.fuel)}</p><p><b>Branch:</b> ${esc(pendingVehicle.branch)}</p></div>`;document.getElementById("vehicleModal").classList.add("show")}
function closeVehicleModal(){document.getElementById("vehicleModal").classList.remove("show")}
function confirmVehicleAudit(){selectedVehicle=pendingVehicle;closeVehicleModal();startAudit()}
async function loadBranchVehicles(){const b=document.getElementById("branchSelect").value;if(!b)return status("branchStatus","Select a branch.","error");try{const d=await apiGet({action:"getVehiclesByBranch",branch:b});if(!d.success)throw Error(d.message);document.getElementById("branchResults").style.display="block";document.getElementById("branchCount").textContent=`Total vehicles in ${b}: ${d.count}`;document.getElementById("branchTableBody").innerHTML=(d.vehicles||[]).map((v,i)=>`<tr><td>${esc(v.vehicleNumber)}</td><td>${esc(v.vehicleName)}</td><td>${esc(v.variant)}</td><td>${esc(v.fuel)}</td><td>${esc(v.branch)}</td><td><button class="btn success" onclick="branchVehicle(${i})">AUDIT</button></td></tr>`).join("");window._branchVehicles=d.vehicles||[]}catch(e){status("branchStatus",e.message,"error")}}
function branchVehicle(i){pendingVehicle=window._branchVehicles[i];openVehicleModal()}
function startAudit(){document.getElementById("auditForm").style.display="block";document.getElementById("selectedVehicleBox").textContent=`Selected: ${selectedVehicle.vehicleNumber} — ${selectedVehicle.vehicleName} — ${selectedVehicle.branch}`;document.getElementById("auditVehicleNumber").textContent=selectedVehicle.vehicleNumber;document.getElementById("auditVehicleMeta").textContent=`${selectedVehicle.vehicleName} • ${selectedVehicle.variant} • ${selectedVehicle.fuel} • ${selectedVehicle.branch}`;buildParts();resetAudit(false);document.querySelectorAll(".nav button").forEach(b=>{if(b.textContent==="Start Audit")b.click()});window.scrollTo({top:0,behavior:"smooth"});apiPost({action:"recordAttendance",branch:selectedVehicle.branch,auditorName:document.getElementById("auditorName").value||"Pending",employeeId:document.getElementById("auditorId").value||"Pending",attendanceAction:"VEHICLE_OPENED"}).catch(()=>{})}
function toggleBlock(id,on){document.getElementById(id).style.display=on?"block":"none"}
function radio(name){const e=document.querySelector(`input[name="${name}"]:checked`);return e?e.value:""}
function calcKm(){const a=Number(document.getElementById("logBookKm").value),b=Number(document.getElementById("odometerKm").value),d=(a&&b)?b-a:"";document.getElementById("kmDifference").value=d;document.getElementById("kmStatus").textContent=(d==="")?"Enter both kilometer values.":(d===0?"No kilometer difference.":`Difference: ${d>0?"+":""}${d} km`)}
function buildParts(){document.getElementById("parts").innerHTML=BODY_PARTS.map(p=>`<label class="part"><input type="checkbox" value="${esc(p)}" onchange="renderPartMedia()"> ${esc(p)}</label>`).join("")}
function mediaButtons(key){return `<div class="actions"><button class="btn secondary" onclick="openMedia('${key}','photo')">TAKE PHOTO</button><button class="btn secondary" onclick="openMedia('${key}','video')">TAKE VIDEO</button><button class="btn secondary" onclick="openMedia('${key}','file')">ADD FILE</button></div><div class="media-row" id="mediaRow_${btoa(unescape(encodeURIComponent(key))).replace(/=/g,'')}"></div>`}
function targetId(key){return btoa(unescape(encodeURIComponent(key))).replace(/=/g,'')}
function renderMedia(key){const arr=mediaArray(key),el=document.getElementById("mediaRow_"+targetId(key));if(!el)return;el.innerHTML=arr.map((m,i)=>`<div class="media-item">${m.type.startsWith("video")?`<video src="${m.data}" controls></video>`:`<img src="${m.data}" alt="">`}<div><span>${esc(m.name).slice(0,18)}</span><button class="smallbtn" onclick="removeMedia('${key.replace(/'/g,"\\'")}',${i})">REMOVE</button></div></div>`).join("")}
function mediaArray(key){if(key==="odo")return mediaStore.odo;if(key==="spare")return mediaStore.spare;if(key==="condition")return mediaStore.condition;if(key==="other")return mediaStore.other;if(key.startsWith("part:")){const p=key.slice(5);if(!mediaStore.parts[p])mediaStore.parts[p]=[];return mediaStore.parts[p]}return []}
function addMedia(key,file){mediaArray(key).push(file);renderMedia(key)}
function removeMedia(key,i){mediaArray(key).splice(i,1);renderMedia(key)}
function renderSingleMedia(container,key){document.getElementById(container).innerHTML=`<div class="media-box"><b>Evidence</b>${mediaButtons(key)}</div>`;renderMedia(key)}
function renderPartMedia(){const selected=[...document.querySelectorAll("#parts input:checked")].map(x=>x.value);document.getElementById("partMediaArea").innerHTML=selected.map(p=>`<div class="media-box"><b>${esc(p)}</b>${mediaButtons("part:"+p)}</div>`).join("");selected.forEach(p=>renderMedia("part:"+p))}
function renderConditionMedia(){renderSingleMedia("conditionMedia","condition")}
function renderSpareMedia(){renderSingleMedia("spareMedia","spare")}
function renderOdoMedia(){renderSingleMedia("odoMediaArea","odo")}
function openMedia(key,kind){mediaTarget=key;const el=document.getElementById(kind==="photo"?"photoInput":kind==="video"?"videoInput":"fileInput");el.value="";el.onchange=async()=>{for(const f of [...el.files]){try{addMedia(key,await fileToData(f))}catch(e){alert(e.message)}}};el.click()}
function fileToData(f){return new Promise((resolve,reject)=>{if(f.size>25*1024*1024)reject(Error("File is larger than 25 MB. Use a shorter video or smaller file."));const r=new FileReader();r.onload=()=>resolve({name:f.name,type:f.type||"application/octet-stream",data:r.result});r.onerror=()=>reject(Error("Could not read file."));r.readAsDataURL(f)})}
function collectAudit(){const damage=radio("damage"),parts=[...document.querySelectorAll("#parts input:checked")].map(x=>x.value),a={action:"submitAudit",vehicle:selectedVehicle,logBookKm:Number(document.getElementById("logBookKm").value)||0,odometerKm:Number(document.getElementById("odometerKm").value)||0,odoVariation:radio("odo"),odoRemarks:document.getElementById("odoRemarks").value.trim(),damage,damageParts:parts,damageRemarks:document.getElementById("damageRemarks").value.trim(),vehicleCondition:radio("condition"),conditionRemarks:document.getElementById("conditionRemarks").value.trim(),spareWheel:radio("spare"),spareRemarks:document.getElementById("spareRemarks").value.trim(),otherIssue:radio("other"),otherRemarks:document.getElementById("otherRemarks").value.trim(),auditorName:document.getElementById("auditorName").value.trim(),auditorId:document.getElementById("auditorId").value.trim(),media:{odo:mediaStore.odo,spare:mediaStore.spare,condition:mediaStore.condition,other:mediaStore.other,parts:mediaStore.parts}};return a}
async function submitAudit(){if(!selectedVehicle)return status("auditStatus","Select a vehicle first.","error");const a=collectAudit();if(!a.logBookKm||!a.odometerKm||!a.odoVariation||!a.damage||!a.vehicleCondition||!a.spareWheel||!a.otherIssue||!a.auditorName||!a.auditorId)return status("auditStatus","Complete kilometer, checklist and auditor fields.","error");if(a.damage==="Yes"&&!a.damageParts.length)return status("auditStatus","Select at least one affected body part.","error");if(a.otherIssue==="Yes"&&!a.otherRemarks)return status("auditStatus","Add other issue remarks.","error");const btn=document.getElementById("submitAuditBtn");btn.disabled=true;status("auditStatus","Saving audit and evidence. Please wait...","info");try{const d=await apiPost(a);if(!d.success)throw Error(d.message);status("auditStatus",`Audit saved: ${d.auditId}. Evidence files: ${d.mediaCount}`,"success");setTimeout(()=>resetAudit(true),1200)}catch(e){status("auditStatus","Could not save audit: "+e.message,"error")}finally{btn.disabled=false}}
function resetAudit(clear=true){mediaStore={odo:[],spare:[],condition:[],other:[],parts:{}};document.querySelectorAll('#auditForm input[type="radio"],#auditForm input[type="checkbox"]').forEach(x=>x.checked=false);["logBookKm","odometerKm","kmDifference","odoRemarks","damageRemarks","conditionRemarks","spareRemarks","otherRemarks","auditorName","auditorId"].forEach(id=>document.getElementById(id).value="");["odoIssue","damageIssue","otherIssue"].forEach(id=>toggleBlock(id,false));document.getElementById("partMediaArea").innerHTML="";document.getElementById("conditionMedia").innerHTML="";document.getElementById("spareMedia").innerHTML="";document.getElementById("media_odo")&&(document.getElementById("media_odo").innerHTML="");document.getElementById("odoMediaArea")&&(document.getElementById("odoMediaArea").innerHTML="");document.getElementById("media_other").innerHTML="";if(clear){selectedVehicle=null;document.getElementById("auditForm").style.display="none";document.getElementById("selectedVehicleBox").textContent="Select a vehicle from Search or Branches."}}
async function loadHistory(){try{status("historyStatus","Loading history...","info");const d=await apiGet({action:"getAuditHistory",vehicleNumber:document.getElementById("historyVehicle").value.trim(),branch:document.getElementById("historyBranch").value});if(!d.success)throw Error(d.message);hide("historyStatus");const rs=d.records||[];document.getElementById("historyResults").innerHTML=rs.length?`<div class="table-wrap"><table class="table"><thead><tr><th>ID</th><th>Time</th><th>Vehicle</th><th>Branch</th><th>Auditor</th><th>Log KM</th><th>Odo KM</th><th>Diff</th><th>Variation</th><th>Damage</th><th>Condition</th><th>Spare</th><th>Other</th><th>Media</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${esc(r.auditId)}</td><td>${esc(r.timestamp)}</td><td>${esc(r.vehicleNumber)}</td><td>${esc(r.branch)}</td><td>${esc(r.auditorName)}</td><td>${esc(r.logBookKm)}</td><td>${esc(r.odometerKm)}</td><td>${esc(r.kmDifference)}</td><td>${esc(r.odoVariation)}</td><td>${esc(r.damage)}</td><td>${esc(r.vehicleCondition)}</td><td>${esc(r.spareWheel)}</td><td>${esc(r.otherIssue)}</td><td>${esc(r.mediaCount)}</td></tr>`).join("")}</tbody></table></div>`:"<div class='muted'>No audit records found.</div>"}catch(e){status("historyStatus",e.message,"error")}}
function addTransferRow(){const wrap=document.getElementById("transferRows"),row=document.createElement("div");row.className="transfer-row";row.innerHTML=`<div><label>Other Showroom</label><input class="trBranch"></div><div><label>Count</label><input class="trCount" type="number" min="0" value="0" oninput="syncTransferTotal()"></div><div><label>Details</label><input class="trDetails" placeholder="Vehicle numbers / reason"></div><button class="btn danger" onclick="this.parentElement.remove();syncTransferTotal()">REMOVE</button>`;wrap.appendChild(row);syncTransferTotal()}
function syncTransferTotal(){let n=0;document.querySelectorAll(".trCount").forEach(e=>n+=Number(e.value)||0);document.getElementById("transferTotal").value=n;recalcClosing()}
function recalcClosing(){const total=Number(document.getElementById("totalTD").value)||0,vals=["inShowroom","outTD","underWashing","underBodyShop","transferTotal"].map(id=>Number(document.getElementById(id).value)||0),accounted=vals.reduce((a,b)=>a+b,0),diff=accounted-total;document.getElementById("accountedTotal").textContent=accounted;document.getElementById("balanceText").textContent=!total?"Enter TOTAL TEST DRIVE.":diff===0?"BALANCED — Accounted count equals Total Test Drive.":diff>0?`OVER BY ${diff} VEHICLE(S) — CHECK.`:`SHORT BY ${Math.abs(diff)} VEHICLE(S) — CHECK.`}
function transferDetails(){return [...document.querySelectorAll(".transfer-row")].map(r=>({showroom:r.querySelector(".trBranch").value.trim(),count:Number(r.querySelector(".trCount").value)||0,details:r.querySelector(".trDetails").value.trim()})).filter(x=>x.showroom||x.count||x.details)}
async function submitBranchClosing(){const total=Number(document.getElementById("totalTD").value)||0,accounted=Number(document.getElementById("accountedTotal").textContent)||0;if(!document.getElementById("closingBranch").value||!document.getElementById("closingDate").value||!total||!document.getElementById("closingAuditor").value.trim()||!document.getElementById("closingAuditorId").value.trim())return status("closingStatus","Complete branch, date, total and auditor details.","error");if(accounted!==total)return status("closingStatus",`Cannot save: TOTAL ${total}, ACCOUNTED ${accounted}.`,"error");try{const d=await apiPost({action:"submitBranchClosing",branch:document.getElementById("closingBranch").value,auditDate:document.getElementById("closingDate").value,totalTD:total,inShowroom:Number(document.getElementById("inShowroom").value)||0,outForTestDrive:Number(document.getElementById("outTD").value)||0,underWashing:Number(document.getElementById("underWashing").value)||0,underBodyShop:Number(document.getElementById("underBodyShop").value)||0,transferToOtherShowrooms:Number(document.getElementById("transferTotal").value)||0,transferDetails:transferDetails(),auditorName:document.getElementById("closingAuditor").value.trim(),employeeId:document.getElementById("closingAuditorId").value.trim(),remarks:document.getElementById("closingRemarks").value.trim()});if(!d.success)throw Error(d.message);status("closingStatus",d.ppt&&d.ppt.success?"Branch closing saved: "+d.closingId+" • PPT generated successfully.":"Branch closing saved: "+d.closingId+(d.pptError?" • PPT generation failed: "+d.pptError:""),d.ppt&&d.ppt.success?"success":"warn");if(d.ppt&&d.ppt.success){document.getElementById("pptHistory").innerHTML='<div class="status show success"><a href="'+d.ppt.presentationUrl+'" target="_blank">OPEN GOOGLE SLIDES</a> | <a href="'+d.ppt.pptFileUrl+'" target="_blank">OPEN PPTX</a></div>'}}catch(e){status("closingStatus",e.message,"error")}}
function resetClosing(){["closingDate","totalTD","inShowroom","outTD","underWashing","underBodyShop","transferTotal","closingAuditor","closingAuditorId","closingRemarks"].forEach(id=>document.getElementById(id).value="");document.getElementById("transferRows").innerHTML="";recalcClosing()}
async function unlockAdmin(){const u=document.getElementById("adminUsername").value.trim(),p=document.getElementById("adminPassword").value;if(!u||!p)return status("adminLoginStatus","Enter username and password.","error");try{const d=await apiGet({action:"verifyAdmin",username:u,password:p});if(!d.success)return status("adminLoginStatus",d.message,"error");adminSession={username:u,password:p};sessionStorage.setItem(ADMIN_KEY,JSON.stringify(adminSession));showAdmin();loadDashboard();status("adminLoginStatus","Admin unlocked.","success")}catch(e){status("adminLoginStatus",e.message,"error")}}
function showAdmin(){document.getElementById("adminLock").style.display="none";document.getElementById("adminContent").style.display="block"}
function lockAdmin(){adminSession=null;sessionStorage.removeItem(ADMIN_KEY);document.getElementById("adminLock").style.display="block";document.getElementById("adminContent").style.display="none";lockDashboard()}
function lockDashboard(){document.getElementById("dashboardLock").style.display="block";document.getElementById("dashboardContent").style.display="none"}
async function addBranch(){if(!adminSession)return;try{const d=await apiPost({action:"addBranch",branch:document.getElementById("newBranch").value.trim(),adminUsername:adminSession.username,adminPassword:adminSession.password});if(!d.success)throw Error(d.message);status("addBranchStatus",d.message,"success");document.getElementById("newBranch").value="";loadBranches()}catch(e){status("addBranchStatus",e.message,"error")}}
async function addVehicle(){if(!adminSession)return;try{const d=await apiPost({action:"addVehicle",vehicleNumber:document.getElementById("addVehicleNumber").value.trim(),vehicleName:document.getElementById("addVehicleName").value.trim(),variant:document.getElementById("addVariant").value.trim(),fuel:document.getElementById("addFuel").value,branch:document.getElementById("addBranchSelect").value,adminUsername:adminSession.username,adminPassword:adminSession.password});if(!d.success)throw Error(d.message);status("addVehicleStatus",d.message,"success");["addVehicleNumber","addVehicleName","addVariant"].forEach(id=>document.getElementById(id).value="");loadBranches()}catch(e){status("addVehicleStatus",e.message,"error")}}
async function loadDashboard(){if(!adminSession && !(currentUser&&(currentUser.role==='MANAGEMENT'||currentUser.role==='AUDITOR')))return lockDashboard();document.getElementById("dashboardLock").style.display="none";document.getElementById("dashboardContent").style.display="block";try{const d=await apiGet({action:"getDashboard"});loadManagementDashboard();if(!d.success)throw Error(d.message);document.getElementById("dashStats").innerHTML=[["TOTAL TD VEHICLES",d.totalVehicles],["AUDITS COMPLETED",d.totalAudits],["OPEN ISSUES",d.openIssues]].map(x=>`<div class="stat"><div class="lbl">${x[0]}</div><div class="num">${x[1]}</div></div>`).join("");document.getElementById("branchDashboard").innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Branch</th><th>TD Vehicles</th><th>Audits</th><th>Latest Closing</th><th>Status</th></tr></thead><tbody>${d.branches.map(b=>`<tr><td>${esc(b.branch)}</td><td>${b.vehicleCount}</td><td>${b.auditCount}</td><td>${esc(b.latestClosing)}</td><td>${esc(b.closingStatus)}</td></tr>`).join("")}</tbody></table></div>`;renderAttendance(d.attendance)}catch(e){status("dashStatus",e.message,"error")}}
function renderAttendance(a){if(!a||!a.dates.length)return document.getElementById("attendanceChart").innerHTML="<div class='muted'>No attendance records yet.</div>";let h="<table><thead><tr><th>Branch</th>"+a.dates.map(d=>`<th>${esc(d)}</th>`).join("")+"</tr></thead><tbody>"+a.series.map(s=>`<tr><td>${esc(s.branch)}</td>${s.values.map(v=>`<td>${v}</td>`).join("")}</tr>`).join("")+"</tbody></table>";document.getElementById("attendanceChart").innerHTML=h}
async function generateReports(){if(!adminSession)return lockDashboard();status("dashStatus","Generating Google Sheet, Excel and PDF...","info");try{const d=await apiPost({action:"generateReports",adminUsername:adminSession.username,adminPassword:adminSession.password});if(!d.success)throw Error(d.message);document.getElementById("dashboardReports").innerHTML=`<div class="status show success">Reports ready: <a href="${d.googleSheetUrl}" target="_blank">Google Sheet</a> • <a href="${d.excelUrl}" target="_blank">Excel</a> • <a href="${d.pdfUrl}" target="_blank">PDF</a></div>`;status("dashStatus","Reports generated.","success")}catch(e){status("dashStatus","Report generation failed: "+e.message,"error")}}
async function loadReportLinks(){try{const d=await apiGet({action:"getReportLinks"});if(!d.success)throw Error(d.message);document.getElementById("reportLinksHistory").innerHTML=d.reports.length?`<h3 style="margin-top:16px">Generated Reports</h3><div class="table-wrap"><table class="table"><thead><tr><th>Created</th><th>Google Sheet</th><th>Excel</th><th>PDF</th></tr></thead><tbody>${d.reports.map(r=>`<tr><td>${esc(r.createdAt)}</td><td><a target="_blank" href="${r.sheetUrl}">OPEN</a></td><td><a target="_blank" href="${r.excelUrl}">DOWNLOAD</a></td><td><a target="_blank" href="${r.pdfUrl}">DOWNLOAD</a></td></tr>`).join("")}</tbody></table></div>`:"<div class='muted'>No reports generated yet.</div>"}catch(e){status("historyStatus",e.message,"error")}}

/* ================= PHASE 4 FRONTEND ================= */
let currentUser=JSON.parse(sessionStorage.getItem('kiaAuditUserV4')||'null');
function setRoleBadge(){var e=document.getElementById('roleBadge');if(currentUser){e.style.display='inline-block';e.textContent=currentUser.role+' • '+currentUser.name;}else e.style.display='none';}
function can(role){return currentUser && (currentUser.role==='ADMIN' || currentUser.role===role);}
function populatePhase4Selectors(){var opts='<option value="">All Branches</option>'+(window._branches||[]).map(function(b){return '<option>'+esc(b)+'</option>';}).join('');['globalBranch','repeatBranch','userBranch','pptBranch'].forEach(function(id){var e=document.getElementById(id);if(e)e.innerHTML=opts;});}
async function globalSearch(){try{status('searchStatus','Searching complete audit history...','info');var d=await apiGet({action:'globalSearch',q:document.getElementById('globalQuery').value.trim(),branch:document.getElementById('globalBranch').value,dateFrom:document.getElementById('globalFrom').value,dateTo:document.getElementById('globalTo').value});if(!d.success)throw Error(d.message);var a=d.audits||[],i=d.issues||[];document.getElementById('globalSearchResults').innerHTML='<h3>Audit Records ('+a.length+')</h3>'+(a.length?'<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Vehicle</th><th>Branch</th><th>Auditor</th><th>ODO</th><th>Damage</th><th>Condition</th><th>Other</th></tr></thead><tbody>'+a.map(function(r){return '<tr><td>'+esc(r.timestamp)+'</td><td><b>'+esc(r.vehicleNumber)+'</b></td><td>'+esc(r.branch)+'</td><td>'+esc(r.auditor)+'</td><td>'+esc(r.odo)+'</td><td>'+esc(r.damage)+'</td><td>'+esc(r.condition)+'</td><td>'+esc(r.other)+'</td></tr>';}).join('')+'</tbody></table></div>':'<div class="muted">No matching audits.</div>')+'<h3 style="margin-top:18px">Matching Findings ('+i.length+')</h3>'+(i.length?'<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Vehicle</th><th>Branch</th><th>Finding</th><th>Severity</th><th>Observation</th></tr></thead><tbody>'+i.map(function(r){return '<tr><td>'+esc(formatClientDate(r.timestamp))+'</td><td>'+esc(r.vehicleNumber)+'</td><td>'+esc(r.branch)+'</td><td>'+esc(r.title)+'</td><td class="'+String(r.severity||'').toLowerCase()+'">'+esc(r.severity)+'</td><td>'+esc(r.observation)+'</td></tr>';}).join('')+'</tbody></table></div>':'<div class="muted">No matching findings.</div>');status('searchStatus','Search completed.','success')}catch(e){status('searchStatus',e.message,'error')}}
function clearGlobalSearch(){['globalQuery','globalFrom','globalTo'].forEach(function(id){var e=document.getElementById(id);if(e)e.value=''});document.getElementById('globalSearchResults').innerHTML='';hide('searchStatus')}
function formatClientDate(v){return v||''}
async function loadRepeats(){try{status('repeatStatus','Checking historical audit records...','info');var d=await apiGet({action:'getRepeatFindings',branch:document.getElementById('repeatBranch').value,vehicleNumber:document.getElementById('repeatVehicle').value.trim()});if(!d.success)throw Error(d.message);var rs=d.repeats||[];document.getElementById('repeatResults').innerHTML=rs.length?rs.map(function(r){return '<div class="repeat-row"><div><span class="badge">REPEATED ×'+r.count+'</span> <b>'+esc(r.title)+'</b></div><div class="muted" style="margin-top:5px">'+esc(r.branch)+' • '+esc(r.vehicleNumber)+' • First: '+esc(r.firstDate)+' • Latest: '+esc(r.lastDate)+'</div><div style="margin-top:8px">Severity: <span class="'+String(r.severity).toLowerCase()+'">'+esc(r.severity)+'</span></div>'+r.audits.map(function(a){return '<div class="muted" style="margin-top:5px">'+esc(a.date)+' — '+esc(a.auditId)+' — '+esc(a.observation)+'</div>';}).join('')+'</div>';}).join(''):'<div class="status show success">No repeated observations found for the selected filter.</div>';status('repeatStatus','Repeat-finding analysis completed.','success')}catch(e){status('repeatStatus',e.message,'error')}}
async function loadManagementDashboard(){try{var d=await apiGet({action:'getManagementDashboard'});if(!d.success)throw Error(d.message);document.getElementById('dashStats').innerHTML=[['TD VEHICLES',d.kpis.vehicles],['AUDITS',d.kpis.audits],['FINDINGS',d.kpis.findings],['HIGH',d.kpis.high],['MEDIUM',d.kpis.medium],['REPEAT',d.kpis.repeat]].map(function(x){return '<div class="stat"><div class="lbl">'+x[0]+'</div><div class="num">'+x[1]+'</div></div>';}).join('');document.getElementById('branchDashboard').innerHTML='<div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>Branch</th><th>Vehicles</th><th>Audits</th><th>Findings</th><th>High</th><th>Repeat</th><th>Score</th></tr></thead><tbody>'+d.branches.map(function(b,i){return '<tr><td class="rank">'+(i+1)+'</td><td><b>'+esc(b.branch)+'</b></td><td>'+b.vehicles+'</td><td>'+b.audits+'</td><td>'+b.findings+'</td><td class="high">'+b.high+'</td><td>'+b.repeat+'</td><td><b>'+b.score+'%</b></td></tr>';}).join('')+'</tbody></table></div>';document.getElementById('attendanceChart').innerHTML='<div class="grid"><div class="management-card card"><h3>Finding Categories</h3>'+Object.keys(d.categories).map(function(k){return '<div style="display:flex;justify-content:space-between;padding:7px 0;border-bottom:1px solid var(--line)"><span>'+esc(k)+'</span><b>'+d.categories[k]+'</b></div>';}).join('')+'</div><div class="management-card card"><h3>Audit Trend</h3>'+d.trend.slice(-12).map(function(t){return '<div style="display:flex;justify-content:space-between;padding:7px 0;border-bottom:1px solid var(--line)"><span>'+esc(t.date)+'</span><b>'+t.audits+'</b></div>';}).join('')+'</div></div>';populatePhase4Selectors()}catch(e){status('dashStatus',e.message,'error')}}
async function createBranchPpt(){if(!currentUser)return;var b=document.getElementById('pptBranch').value,d=document.getElementById('pptDate').value;if(!b||!d)return status('pptStatus','Select branch and audit date.','error');status('pptStatus','Creating official KIA Branch Audit presentation...','info');try{var r=await apiPost({action:'createBranchPpt',branch:b,auditDate:d,createdBy:currentUser.name});if(!r.success)throw Error(r.message);document.getElementById('pptStatus').innerHTML='';status('pptStatus','PPT created successfully.','success');document.getElementById('pptHistory').innerHTML='<div class="status show success"><a href="'+r.presentationUrl+'" target="_blank">OPEN GOOGLE SLIDES</a> &nbsp; | &nbsp; <a href="'+r.pptFileUrl+'" target="_blank">OPEN PPTX FILE</a> &nbsp; | Version '+r.version+'</div>';loadPptHistory()}catch(e){status('pptStatus','PPT generation failed: '+e.message,'error')}}
async function loadPptHistory(){try{var d=await apiGet({action:'getPptHistory',branch:document.getElementById('pptBranch').value});if(!d.success)throw Error(d.message);document.getElementById('pptHistory').innerHTML=d.items.length?'<h4 style="margin-top:15px">Presentation History</h4><div class="table-wrap"><table class="table"><thead><tr><th>Created</th><th>Branch</th><th>Audit Date</th><th>Version</th><th>Slides</th><th>Findings</th><th></th></tr></thead><tbody>'+d.items.map(function(r){return '<tr><td>'+esc(r.createdAt)+'</td><td>'+esc(r.branch)+'</td><td>'+esc(r.auditDate)+'</td><td>v'+esc(r.version)+'</td><td>'+esc(r.slideCount)+'</td><td>'+esc(r.issueCount)+'</td><td><a href="'+r.presentationUrl+'" target="_blank">SLIDES</a> | <a href="'+r.pptFileUrl+'" target="_blank">PPTX</a></td></tr>';}).join('')+'</tbody></table></div>':'<div class="muted">No PPT history yet.</div>'}catch(e){status('pptStatus',e.message,'error')}}
async function saveUser(){if(!currentUser||currentUser.role!=='ADMIN')return status('userStatus','Admin access required.','error');try{var d=await apiPost({action:'upsertUser',username:document.getElementById('userUsername').value.trim(),password:document.getElementById('userPassword').value,name:document.getElementById('userName').value.trim(),role:document.getElementById('userRole').value,branch:document.getElementById('userBranch').value,adminUsername:currentUser.username,adminPassword:currentUser.password});if(!d.success)throw Error(d.message);status('userStatus',d.message,'success');loadUsers()}catch(e){status('userStatus',e.message,'error')}}
async function loadUsers(){if(!currentUser||currentUser.role!=='ADMIN')return;try{var d=await apiGet({action:'getUsers',username:currentUser.username,password:currentUser.password});document.getElementById('userList').innerHTML='<div class="table-wrap"><table class="table"><thead><tr><th>Username</th><th>Name</th><th>Role</th><th>Branch</th><th>Active</th></tr></thead><tbody>'+d.users.map(function(u){return '<tr><td>'+esc(u.username)+'</td><td>'+esc(u.name)+'</td><td>'+esc(u.role)+'</td><td>'+esc(u.branch)+'</td><td>'+esc(u.active)+'</td></tr>';}).join('')+'</tbody></table></div>'}catch(e){status('userStatus',e.message,'error')}}
async function loginPhase4(){var u=prompt('KIA Audit username');if(!u)return;var p=prompt('KIA Audit password');if(!p)return;try{var d=await apiGet({action:'verifyUser',username:u,password:p});if(!d.success)throw Error(d.message);currentUser=d.user;currentUser.password=p;sessionStorage.setItem('kiaAuditUserV4',JSON.stringify(currentUser));adminSession=currentUser.role==='ADMIN'?{username:u,password:p}:null;if(adminSession)sessionStorage.setItem(ADMIN_KEY,JSON.stringify(adminSession));setRoleBadge();applyRoleUI();alert('Signed in as '+currentUser.role)}catch(e){alert(e.message)}}
function applyRoleUI(){var isAdmin=currentUser&&currentUser.role==='ADMIN';var isMgmt=currentUser&&currentUser.role==='MANAGEMENT';document.querySelectorAll('.nav button').forEach(function(b){var t=b.textContent;if(t==='Admin' && !isAdmin)b.style.display='none';});if(isMgmt){document.querySelectorAll('#auditSection,#branchSection,#closingSection').forEach(function(e){if(e)e.style.display='none'});}populatePhase4Selectors();}
function addPhase4LoginButton(){var nav=document.querySelector('.nav');if(!document.getElementById('phase4LoginBtn')){var b=document.createElement('button');b.id='phase4LoginBtn';b.className='secondary';b.textContent=currentUser?'SIGN OUT':'SIGN IN';b.onclick=function(){if(currentUser){currentUser=null;sessionStorage.removeItem('kiaAuditUserV4');sessionStorage.removeItem(ADMIN_KEY);location.reload();}else loginPhase4()};nav.appendChild(b)}}

function init(){if(!currentUser && adminSession){currentUser={username:adminSession.username,name:"Admin",role:"ADMIN",password:adminSession.password};}setRoleBadge();addPhase4LoginButton();if(currentUser&&currentUser.role==='ADMIN'){showAdmin();loadDashboard();loadUsers();}loadBranches();buildParts();document.getElementById("closingDate").value=new Date().toISOString().slice(0,10);setTimeout(function(){populatePhase4Selectors();if(currentUser)applyRoleUI();},500)}
init();
